name: jksoam
on: 
  push: 
    branches: 
      - main
      - feature
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bash
        run: |
          pwd
          ls
          whoami
  apply:
    runs-on: ubuntu-24.04
    if: always()
    steps:
      - name: bash2
        run: |
          echo "my name is jksoam"
    

    
