name: experimet01
on: 
  push:
    branches: 
      - main
      - dev
jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bashAction
        run: |
          pwd
          ls
          exit 1
  plan:
   runs-on: ubuntu-24.04
   #needs: install
   steps:
     - name: plan
       run: |
         echo "my name is jksoam"
         exit 1
  apply:
    runs-on: ubuntu-24.04
    needs: 
     - plan
     - install
    if: failure() && github.ref == 'refs/heads/main'
    steps:
      - name: apply
        run: |
          echo "Applied"
       
   
   
          
      
  

  
